export enum MessageQueueType {
  CREATE_BUYER = "CREATE_BUYER",
  UPDATE_BUYER = "UPDATE_BUYER",
  SEND_FORGOT_PASSWORD_EMAIL = "SEND_FORGOT_PASSWORD_EMAIL",
  SEND_VERIFY_EMAIL = "SEND_VERIFY_EMAIL",
  UPDATE_SELLER_GIG_COUNT = "UPDATE_SELLER_GIG_COUNT",
  CREATE_ORDER = "CREATE_ORDER",
  APPROVE_ORDER = "APPROVE_ORDER",
  CANCEL_ORDER = "CANCEL_ORDER",
  PURCHASED_GIGS = "PURCHASED_GIGS",
  BUYER_REVIEW = "BUYER_REVIEW",
  UPDATE_GIG = "UPDATE_GIG"
}
